-- orders.pickup_code — what a customer shows at the counter (roadmap Step 3).
--
-- Run as `postgres`. Idempotent: safe to re-run.
--
-- ── What it is, and what it is not ─────────────────────────────────────────
-- A short random Crockford-base32 string (lib/fulfilment/collection-code.ts)
-- that FINDS a collection order at a till. It is a lookup key, NOT an
-- authorisation: the counter resolves it store-scoped, and the operator is
-- already authenticated and can see whose order it is. Access control stays
-- what it has always been — UUID plus store scope (CODEBASE §14).
--
-- It is random rather than derived from `order_ref` because that column is
-- sequential and guessable; anyone at a counter could otherwise name someone
-- else's collection.
--
-- ── Why UNIQUE and not UNIQUE-per-store ────────────────────────────────────
-- A till scans a code with no idea which store it belongs to until it resolves
-- one. Global uniqueness means the lookup can be a single indexed equality and
-- the store check is then an assertion rather than part of the key. With 32^8
-- ≈ 1.1e12 values a collision is a retry, not a design problem.
--
-- NULL for every non-pickup order, which is almost all of them — hence the
-- PARTIAL index: a unique index over mostly-NULL is paid for on every insert
-- for nothing.

BEGIN;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS pickup_code text;

CREATE UNIQUE INDEX IF NOT EXISTS orders_pickup_code_key
  ON public.orders (pickup_code)
  WHERE pickup_code IS NOT NULL;

COMMENT ON COLUMN public.orders.pickup_code IS
  'Short random collection code shown at the counter. A LOOKUP key, not a bearer token — access control remains UUID + store scope. NULL for non-pickup orders. Generated by lib/fulfilment/collection-code.ts.';

COMMIT;

-- ── Backfill ────────────────────────────────────────────────────────────────
-- None. Existing pickup orders keep NULL and are found the way they always
-- were — by order reference at the counter. Minting codes for orders whose
-- customers were never sent one would create codes nobody can present.

-- ── Rollback ────────────────────────────────────────────────────────────────
-- BEGIN;
-- DROP INDEX IF EXISTS public.orders_pickup_code_key;
-- ALTER TABLE public.orders DROP COLUMN IF EXISTS pickup_code;
-- COMMIT;
