-- Roadmap Step 2 / returns-exchanges-plan.md §3.2 — the money-out path.
--
-- Run as `postgres`, after pos_12_returns.sql.
--
-- ── THIS IS A NEW FILE, NOT AN EDIT TO pos_12 ──────────────────────────────
-- pos_12_returns.sql has already run in prod, and it creates order_refunds
-- with CREATE TABLE IF NOT EXISTS — so adding a column there is a silent
-- no-op and the column never arrives, while the code happily writes it (the
-- exact failure CODEBASE.md §15b records for subscriptions.scheduled_plan).
-- Anything added to an existing table gets its own file. Always.
--
-- ── Why an idempotency key, when gateway_refund_id is already UNIQUE ───────
-- The UNIQUE index makes the RECORD idempotent. It cannot make the CALL
-- idempotent: you do not have a Razorpay refund id until the call returns,
-- and a timeout is indistinguishable from a failure. Retrying blind refunds
-- the customer twice.
--
-- So the row is written BEFORE any money is asked to move, carrying a key we
-- generated. That key goes to Razorpay as its idempotency header AND into the
-- refund's notes, so:
--   • a retry with the same key returns Razorpay's original refund, and
--   • the reconcile sweep can match a refund we never got a reply for back to
--     the row that requested it — exactly, by id, not by guessing on amount.
--
-- ── Why delivered_at ───────────────────────────────────────────────────────
-- A return window has to start when the parcel LANDED. Measured from
-- created_at, a 7-day window on a 10-day delivery has expired before the
-- customer ever held the goods.

BEGIN;

-- ---------------------------------------------------------------------------
-- order_refunds — the gateway columns
-- ---------------------------------------------------------------------------
ALTER TABLE public.order_refunds
  ADD COLUMN IF NOT EXISTS idempotency_key text;

-- Why a refund happened. order_returns.reason covers goods coming back, but a
-- refund can exist with no return at all (a cancellation), and that row is the
-- one a merchant gets asked about months later.
ALTER TABLE public.order_refunds
  ADD COLUMN IF NOT EXISTS reason text;

-- Free-text reference for money moved OUTSIDE any gateway: the UPI
-- transaction id the merchant typed after paying a COD customer back from
-- their own phone. It is the only evidence such a row will ever carry, which
-- is why it is a real column and not a note.
ALTER TABLE public.order_refunds
  ADD COLUMN IF NOT EXISTS reference text;

-- One refund per key. This is what makes a retried refundOrder call safe: the
-- second insert loses, and the caller resumes the FIRST row rather than
-- starting a second payout.
CREATE UNIQUE INDEX IF NOT EXISTS order_refunds_idempotency_key
  ON public.order_refunds (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- The sweep's query: every refund still awaiting an answer from the gateway.
-- Partial, because the overwhelming majority of rows are settled and a full
-- index on `status` would be mostly dead weight.
CREATE INDEX IF NOT EXISTS order_refunds_pending_idx
  ON public.order_refunds (created_at)
  WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- orders.delivered_at
-- ---------------------------------------------------------------------------
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS delivered_at timestamptz;

-- Backfill: orders already marked delivered got there at some point, and
-- updated_at is the closest thing to a timestamp we kept. Approximate, and
-- flagged as such — but a NULL here means "no return window at all" for every
-- historical order, which is worse than an approximation.
--
-- ★ Invariant 1 (a migration may not change what a live store does) is not in
-- tension here: nothing reads delivered_at until the returns settings ship,
-- and those default OFF.
UPDATE public.orders
   SET delivered_at = updated_at
 WHERE status = 'delivered'
   AND delivered_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_delivered_at_idx
  ON public.orders (store_id, delivered_at)
  WHERE delivered_at IS NOT NULL;

COMMENT ON COLUMN public.order_refunds.idempotency_key IS
  'Generated by us BEFORE the gateway call, sent as Razorpay''s idempotency header and in the refund notes. Makes a retried call safe and lets the reconcile sweep match a refund we never got a reply for.';
COMMENT ON COLUMN public.order_refunds.reference IS
  'Merchant-supplied proof for money moved outside any gateway (a UPI transaction id). The only evidence a manual refund row carries.';
COMMENT ON COLUMN public.orders.delivered_at IS
  'When the order actually landed. The return window starts here, not at created_at — a 7-day window on a 10-day delivery would otherwise expire before the parcel arrived.';

COMMIT;

-- ── Rollback ────────────────────────────────────────────────────────────────
-- BEGIN;
-- DROP INDEX IF EXISTS public.orders_delivered_at_idx;
-- DROP INDEX IF EXISTS public.order_refunds_pending_idx;
-- DROP INDEX IF EXISTS public.order_refunds_idempotency_key;
-- ALTER TABLE public.orders        DROP COLUMN IF EXISTS delivered_at;
-- ALTER TABLE public.order_refunds DROP COLUMN IF EXISTS reference;
-- ALTER TABLE public.order_refunds DROP COLUMN IF EXISTS reason;
-- ALTER TABLE public.order_refunds DROP COLUMN IF EXISTS idempotency_key;
-- COMMIT;
